use codec::{Decode, Encode, MaxEncodedLen};
use scale_info::TypeInfo;
use frame_support::{traits::ConstU32, BoundedVec};

use crate::bounds::MAX_METADATA_LEN;
use crate::template::MAX_TEMPLATE_NAME_LEN;

/// A genesis contract offer created by an issuer for a specific user.
///
/// The pallet generates this when an issuer calls `offer_contract`.
/// One active offer per issuer-user pair — creating a new offer for the same
/// user atomically revokes the old one (old deposit returned, new deposit taken).
///
/// The user must submit their signed response (TPM pubkey + OTP) before
/// `expiry_block`, and the offer must still exist in `ContractOffers`.
/// Offer removal is the nonce consumption mechanism — no separate
/// `ConsumedNonces` map.
#[derive(Encode, Decode, Clone, PartialEq, Eq, TypeInfo, MaxEncodedLen)]
#[cfg_attr(feature = "std", derive(Debug))]
#[scale_info(skip_type_params(AccountId, BlockNumber, Balance))]
pub struct ContractOffer<AccountId, BlockNumber, Balance> {
    /// The issuer making this offer.
    pub issuer: AccountId,
    /// The intended recipient. Only this address may respond to this offer.
    pub user: AccountId,
    /// Unique nonce generated by the pallet at offer creation.
    pub nonce: [u8; 32],
    /// Absolute block number after which this offer is no longer valid.
    pub expiry_block: BlockNumber,
    /// Block at which this offer was created.
    pub created_at: BlockNumber,
    /// TTL for the end-user cert, set by the issuer.
    /// Cannot exceed the issuer's own NotAfter at mint time.
    pub ttl_blocks: BlockNumber,
    /// Storage deposit paid by the issuer for this offer.
    pub deposit: Balance,
    /// Issuer-defined metadata that will be embedded immutably in the minted cert.
    pub metadata: BoundedVec<u8, ConstU32<MAX_METADATA_LEN>>,
    /// Template class this offer was issued under. Must reference an
    /// active `CertTemplate` owned by `issuer` at the time of offer
    /// creation. Copied to `CertRecordHot.template_name` at mint.
    pub template_name: BoundedVec<u8, ConstU32<MAX_TEMPLATE_NAME_LEN>>,
}
